# The "Normal" CI for tests and linters and whatnot
name: Rust CI

# Ci should be run on...
on:
  # Every pull request (will need approval for new contributors)
  pull_request:
  # Every push to...
  push:
    branches:
      # The main branch
      - main
      # Not a thing I use personally but some people like having a release branch
      - "release/**"
  # And once a week? 
  # This can catch things like "rust updated and actually regressed something"
  schedule:
    - cron: "11 7 * * 1,4"

# We want all these checks to fail if they spit out warnings
env:
  RUSTFLAGS: -Dwarnings

jobs:
  # Run cargo-vet (taken from the cargo-vet book)
  cargo-vet:
    name: Vet Dependencies
    runs-on: ubuntu-latest
    env:
      CARGO_VET_VERSION: 0.3.0
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update stable && rustup default stable
    - uses: actions/cache@v2
      with:
        path: ${{ runner.tool_cache }}/cargo-vet
        key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
    - name: Add the tool cache directory to the search path
      run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
    - name: Ensure that the tool cache is populated with the cargo-vet binary
      # Currently patching in a fork
      run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} --git https://github.com/Gankra/cargo-vet --branch bots cargo-vet
    - name: Invoke cargo-vet
      # Currently emitting a custom output
      run: cargo vet --output-format=json-full
