name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  # push:
  pull_request:
jobs:
  cargo-vet:
      name: Vet Dependencies
      runs-on: ubuntu-latest
      env:
        CARGO_VET_VERSION: 0.3.0
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repositoryUrl }}
        PR: ${{ github.event.pull_request.number }}
      steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/cargo-vet
          key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
      - name: Add the tool cache directory to the search path
        run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
      - name: Ensure that the tool cache is populated with the cargo-vet binary
        # run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} cargo-vet
        # Currently patching in a fork
        run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} --git https://github.com/Gankra/cargo-vet --branch bots cargo-vet
      - name: Invoke cargo-vet
        # Currently emitting a custom output
        run: cargo vet --locked --output-format=json-full > vet-results.json
        # run: cargo vet --locked --output-format=json > vet-results.json
      - if: ${{ failure() }}
        name: Report Failure
        run: |
          repo=$(echo ${{ env.REPO }} | sed s,git://github.com/,, | sed s,.git,,)
          echo $repo
          cat vet-results.json | jq --arg repo $repo --arg pr ${{ env.PR }} '. + {repo: $repo, pr: $pr}' > vet-results-final.json
          cat vet-results-final.json
          cat vet-results-final.json | curl -X POST --data @- https://cargo-vet-git-gh-app-axo.vercel.app/api/webhooks/receive
          

      
